host: https://staging.commcarehq.org
domain: us-covid-performance
app_id: 765b9d4c97d149b3859f86c229872f97 
domain_user_credential: staging/staging_user_credentials.json
owner_id: 39dfd889c53a4ed7894e68600fd1aee7
case_type: patient
app_config: staging/staging_config.json
